name: isort
on:
  push:
    paths:
      - 'reditools/**py'
      - 'test/**py'
  pull_request:
    paths:
      - 'reditools/**py'
      - 'test/**py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install isort
        run: |
          pip install isort
      - name: Run isort
        run: |
          isort -c reditools/ test/
