on: [push, pull_request]

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: libbz2-dev  zlib1g-dev liblzma-dev build-essential
      - uses: actions/checkout@v6
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: python3 -m pip install .
      - name: Run tests
        run: python3 -m test
